EXEC USP_Properties_Save 1, N'E', N'علاقمند به صحبت و تبادل'
EXEC USP_Properties_Save 2, N'E', N'لذت بردن از گروه ها'
EXEC USP_Properties_Save 3, N'E', N'اول حرف می زنم بعد فکر می کنم'
EXEC USP_Properties_Save 4, N'E', N'گسترش انرژی'
EXEC USP_Properties_Save 5, N'E', N'توجه به بیرون'
EXEC USP_Properties_Save 6, N'E', N'اهل صحبت'
EXEC USP_Properties_Save 7, N'E', N'علاقمند به تنوع و عمل'
EXEC USP_Properties_Save 8, N'E', N'معاشرتی'
EXEC USP_Properties_Save 9, N'E', N'فکر کردن به صدای بلند'
EXEC USP_Properties_Save 10, N'E', N'لذت بردن از بحث'
EXEC USP_Properties_Save 11, N'I', N'علاقمند به تنهایی'
EXEC USP_Properties_Save 12, N'I', N'لذت بردن از صحبت دو نفری'
EXEC USP_Properties_Save 13, N'I', N'اول فکر می کنم بعد حرف می زنم'
EXEC USP_Properties_Save 14, N'I', N'تمرکز انرژی'
EXEC USP_Properties_Save 15, N'I', N'توجه به درون'
EXEC USP_Properties_Save 16, N'I', N'ساکت'
EXEC USP_Properties_Save 17, N'I', N'توجه به یک موضوع در هر زمان'
EXEC USP_Properties_Save 18, N'I', N'در خود فکر کردن'
EXEC USP_Properties_Save 19, N'I', N'لذت بردن از فکر کردن'