EXEC USP_Preferences_Save N'E', N'برون گرا'
EXEC USP_Preferences_Save N'F', N'احساسی بودن'
EXEC USP_Preferences_Save N'I', N'درون گرا'
EXEC USP_Preferences_Save N'J', N'داوری کننده'
EXEC USP_Preferences_Save N'N', N'شمی بودن'
EXEC USP_Preferences_Save N'P', N'ادراکی'
EXEC USP_Preferences_Save N'S', N'حسی بودن'
EXEC USP_Preferences_Save N'T', N'فکری بودن'